INSERT INTO blogful_articles (title, date_published, content)
VALUES
    ('Article 1', now() - '25 days'::INTERVAL, 'This is the content for article 1'),
    ('Article 2', now() - '25 days'::INTERVAL, 'This is the content for article 2'),
    ('Article 3', now() - '22 days'::INTERVAL, 'This is the content for article 3'),
    ('Article 4', now() - '21 days'::INTERVAL, 'This is the content for article 4'),
    ('Article 5', now() - '21 days'::INTERVAL, 'This is the content for article 5'),
    ('Article 6', now() - '21 days'::INTERVAL, 'This is the content for article 6'),
    ('Article 7', now() - '21 days'::INTERVAL, 'This is the content for article 7'),
    ('Article 8', now() - '20 days'::INTERVAL, 'This is the content for article 8'),
    ('Article 9', now() - '18 days'::INTERVAL, 'This is the content for article 9'),
    ('Article 10', now() - '15 days'::INTERVAL, 'This is the content for article 10'),
    ('Article 11', now() - '15 days'::INTERVAL, 'This is the content for article 11'),
    ('Article 12', now() - '14 days'::INTERVAL, 'This is the content for article 12'),
    ('Article 13', now() - '13 days'::INTERVAL, 'This is the content for article 2'),
    ('Article 14', now() - '10 days'::INTERVAL, 'This is the content for article 2'),
    ('Article 15', now() - '8 days'::INTERVAL, 'This is the content for article 2'),
    ('Article 16', now() - '5 days'::INTERVAL, 'This is the content for article 2'),
    ('Article 17', now() - '2 days'::INTERVAL, 'This is the content for article 2'),
    ('Article 18', now(), 'This is the content for article 2'),
    ('Article 19', now(), 'This is the content for article 2'),
    ('Article 20', now(), 'This is the content for article 2'),